#!/bin/sh
#
# $1 = UESP host name (e.g., content1)
#

HOSTNAME=$1
NETWORKFILE="/etc/sysconfig/network"

if [ -z $HOSTNAME ]
then
	echo "     ERROR: Missing host name! Format: uesp-update-hostname HOSTNAME"
	exit -1
fi

/sbin/sysctl kernel.hostname=$HOSTNAME > /dev/null
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to set the host name to '$HOSTNAME'!"
	exit -2
fi

if [ ! -f "$NETWORKFILE" ]
then
	echo "     ERROR: Missing network file '$NETWORKFILE'!"
	exit -3
fi

BACKUPFILE="$NETWORKFILE.backup"
	
if [ ! -f $BACKUPFILE ] 
then
	cp -f $NETWORKFILE $BACKUPFILE
fi

RESULT=`egrep -ic "^[ ^I]*hostname[ ^I]*=[ ^I]*[\"]?.*[\"]?" $NETWORKFILE`

if [ $RESULT -eq 0 ]
then	
	echo -e "\nhostname=$HOSTNAME\n" >> $NETWORKFILE
	RESULT=$?
	
	if [ $RESULT != 0 ]
	then
		echo "     ERROR: Failed to modify file '$NETWORKFILE'!"
		exit -4
	fi	
	
	echo "     WARNING: Added missing hostname entry to end of network file!"
else
	sed -i "s:\(^[ ^I]*hostname[ ^I]*=[ ^I]*[\"]*\).*\([\"]*\):\1\2$HOSTNAME\2:i" $NETWORKFILE
	RESULT=$?
		
	if [ $RESULT != 0 ]
	then
		echo "     ERROR: Failed to modify file '$NETWORKFILE'!"
		exit -5
	fi	
fi

echo "     OK: Updated host name to '$HOSTNAME'!"
exit 0

