#!/bin/sh
#

./uesp-install-contentapps

./uesp-yuminstall "mysql-server"
./uesp-yuminstall "mysql-devel"

/sbin/chkconfig --level 345 mysqld on

if [ $? != 0 ]
then
	echo "     ERROR: Failed to modify run levels for mysqld!"
	exit -1
fi

echo "     OK: Modified run levels for mysqld."
