#!/bin/sh
#
# $1 = Username to modify (defaults to uespkey)
#

KEYPATH="/etc/uesp-keys/"
LOCALKEY="local-uesp-key.pub"
USER="$1"

if [ -z "$USER" ]
then
	USER="uespkey"
	echo "   Using user uespkey"
fi

AUTHKEYPATH="/home/$USER/.ssh"
AUTHKEYS="/home/$USER/.ssh/authorized_keys"

update_from_publickey()
#
# $1 = public key file
#
{
	KEYFILE="$1"
	RESULT=`echo $KEYFILE | egrep "$LOCALKEY"`

	if [ $? == 0 ]
	then
		return 1
	fi

	if [ ! -d $AUTHKEYPATH ]
	then
		mkdir -p $AUTHKEYPATH
		chown $USER:$USER $AUTHKEYPATH
		chmod 700 $AUTHKEYPATH
	fi

	if [ ! -f $AUTHKEYS ]
	then
		touch $AUTHKEYS
		chown $USER:$USER $AUTHKEYS
		chmod 600 $AUTHKEYS
	fi

	echo "   Checking public key '$KEYFILE'..."

	RESULT=`grep -f $KEYFILE $AUTHKEYS`

	if [ $? == 0 ]
	then
		echo "   Key already exists in $AUTHKEYS."
		return 0
	fi

	echo "   Adding key to $AUTHKEYS."
	cat $KEYFILE >> $AUTHKEYS

	return 0
}

for file in $KEYPATH*.pub
do
	update_from_publickey "$file"
done

