#!/bin/sh

echo "Starting uesp-install-lighttpd..."

./uesp-yuminstall "fail2ban"
./uesp-yuminstall "lighttpd"

mkdir -p /var/cache/lighttpd/compress

if [ $? != 0 ]
then
	echo "     ERROR: Failed to create the directory '/var/cache/lighttpd/compress'!"
	exit -1
fi

chown -R apache:apache /var/cache/lighttpd
chown -R apache:apache /var/log/lighttpd

chmod -R o-w /var/cache/lighttpd

if [ $? != 0 ]
then
	echo "     ERROR: Failed to set permissions of cache directory!"
	exit -3
fi

systemctl enable lighttpd

if [ $? != 0 ]
then
	echo "     ERROR: Failed to update systemctl information for lighttpd!"
	exit -8
fi

echo "     OK: Successfully installed lighttpd."
echo "   Note: Config *not* copied!"
exit 0
