#!/bin/sh

./uesp-yuminstall "mariadb"

yum-config-manager --enable remi-php56 > /dev/null

./uesp-yuminstall "php"
./uesp-yuminstall "php-bcmath"
./uesp-yuminstall "php-cli"
./uesp-yuminstall "php-common"
./uesp-yuminstall "php-devel"
./uesp-yuminstall "php-gd"
./uesp-yuminstall "php-intl"
./uesp-yuminstall "php-mbstring"
./uesp-yuminstall "php-mcrypt"
./uesp-yuminstall "php-mysqlnd"
./uesp-yuminstall "php-opcache"
./uesp-yuminstall "php-pdo"
./uesp-yuminstall "php-pear"
./uesp-yuminstall "php-pecl-apcu"
./uesp-yuminstall "php-pecl-jsonc"
./uesp-yuminstall "php-pecl-jsonc-devel"
./uesp-yuminstall "php-pecl-lua"
./uesp-yuminstall "php-pecl-memcache"
./uesp-yuminstall "php-pecl-zip"
./uesp-yuminstall "php-process"
./uesp-yuminstall "php-snmp"
./uesp-yuminstall "php-xml"

./uesp-yuminstall "pkgconfig"

# ./uesp-yuminstall "perl"
# ./uesp-yuminstall "perl-DBD-MySQL"
# ./uesp-yuminstall "perl-DBI"
# ./uesp-yuminstall "perl-String-CRC32"
# ./uesp-yuminstall "perl-URI"

./uesp-yuminstall "httpd"
./uesp-yuminstall "mod_ssl"
systemctl enable httpd

./uesp-install-modevasive

./uesp-yuminstall "ImageMagick"
./uesp-yuminstall "tidy"

./uesp-yuminstall "fail2ban"

./uesp-install-wikidiff2

