#!/bin/sh
#
#
#

./uesp-yuminstall "memcached"

CACHESIZE="1000"
MAXCONN="5000"
PORT="11000"
CONFIG="/etc/sysconfig/memcached"

sed -i "s/CACHESIZE=.*/CACHESIZE=\"$CACHESIZE\"/g" "$CONFIG"
sed -i "s/PORT=.*/PORT=\"$PORT\"/g" "$CONFIG"
sed -i "s/MAXCONN=.*/MAXCONN=\"$MAXCONN\"/g" "$CONFIG"

systemctl enable memcached

if [ $? != 0 ]
then
	echo "     ERROR: Failed to add memcached to systemctl!"
	exit -7
fi

service memcached restart

if [ $? != 0 ]
then
	echo "     ERROR: Failed to start memcached!"
	exit -8
fi

echo "     OK: Successfully installed memcached."
exit 0
