#!/bin/sh
#
# $1 = UESP hostname
#

UESPHOST="$1"

KEYPATH="/etc/uesp-keys/"
LOCALKEY="local-uesp-key.pub"

create_server_key()
#
# $1 = UESP hostname
#
{
	KEYFILE="$1-uesp-key"
	PUBKEYFILE="$KEYFILE.pub"

	ssh-keygen -t dsa -b 1024 -f $KEYFILE

	TMPFILE="$PUBKEYFILE.tmp"
	mv $PUBKEYFILE $TMPFILE

	sed "s/= .*@.*\$/= $1.uesp.net/" $TMPFILE > $PUBKEYFILE

	cp -f $PUBKEYFILE $LOCALKEY

	if [ ! -d $KEYPATH ]
	then
		mkdir $KEYPATH
	fi

	cp -f $PUBKEYFILE $KEYPATH
	cp -f $LOCALKEY $KEYPATH
}


if [ -z $UESPHOST ]
then
	echo "     ERROR: Empty UESP hostname specified!"
	exit -1
fi

create_server_key "$UESPHOST"

