#!/bin/sh
#
# $1=UESP Hostname
# $2=Zabbix Server IP address
#

echo "Starting uesp-install-zabbixagent..."

UESP_HOSTNAME="$1"
SERVERIP="$2"
ZABBIXCONF="/etc/zabbix/zabbix_agentd.conf"

rpm -Uvh https://repo.zabbix.com/zabbix/7.0/alma/9/x86_64/zabbix-agent-7.0.24-release1.el9.x86_64.rpm

# Does nothing in AlmaLinux 9
# yum-config-manager --enable rhel-7-server-optional-rpms > /dev/null

./uesp-yuminstall zabbix-agent

systemctl enable zabbix-agent
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to add the Zabbix agent startup script using systemctl!"
	exit -6
fi

sed -i "s/^Server=.*/Server=$SERVERIP/g" "$ZABBIXCONF"
sed -i "s/^ServerActive=.*/ServerActive=$SERVERIP/g" "$ZABBIXCONF"
sed -i "s/^Hostname=.*/Hostname=$UESP_HOSTNAME/g" "$ZABBIXCONF"

service zabbix-agent restart

# sed -i "s/Server=(.*)/Server=10.12.222.25/g" "/etc/zabbix/zabbix_agentd.conf"

echo "     OK: Successfully installed the Zabbix agent!"
