#!/bin/sh

echo "Starting uesp-install-denyhosts..."

pushd . > /dev/null
cd denyhosts

python setup.py install > /dev/null
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to install the DenyHosts Python application!"
	exit -1
fi

cp -f /usr/share/denyhosts/denyhosts.cfg-dist /usr/share/denyhosts/denyhosts.cfg
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to create the DenyHosts configuration file!"
	exit -1
fi

HOSTNAME=`hostname`
sed -i -e"s/denyhosts@localhost/denyhosts@$HOSTNAME/" /usr/share/denyhosts/denyhosts.cfg

if [ $? != 0 ]
then
	echo "     WARNING: Failed to modify denyhosts send e-mail address!"
fi

cp -f /usr/share/denyhosts/daemon-control-dist /usr/share/denyhosts/daemon-control
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to create the DenyHosts daemon file!"
	exit -2
fi

chown root /usr/share/denyhosts/daemon-control
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to change the owner of the DenyHosts daemon-control file!"
	exit -3
fi

chmod 700 /usr/share/denyhosts/daemon-control
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to change the permissions of the DenyHosts daemon-control file!"
	exit -4
fi

if [ ! -d /var/log/denyhosts ]
then
	mkdir /var/log/denyhosts
	RESULT=$?

	if [ $RESULT != 0 ]
	then
		echo "     WARNING: Failed to create the DenyHosts log directory '/var/log/denyhosts'!"
	fi
fi

ln -f -s /usr/share/denyhosts/daemon-control /etc/init.d/denyhosts
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to add DenyHosts startup script to '/etc/init.d/'!"
	exit -5
fi

/sbin/chkconfig --add denyhosts
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to add DenyHosts startup script using chkconfig!"
	exit -6
fi

ln -fs /usr/share/denyhosts/denyhosts.cfg /etc/denyhosts.cfg
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to create link to denyhosts.cfg in /etc/!"
fi

/etc/init.d/denyhosts restart > /dev/null
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to start DenyHosts!"
	exit -8
fi

echo "     OK: Successfully started DenyHosts!"

popd > /dev/null

echo "     OK: Installed the DenyHosts Python application."
exit 0
