#!/bin/sh
#
# $1=UESP Hostname
# $2=Zabbix Server IP address
#

echo "Starting uesp-install-zabbixagent..."

UESP_HOSTNAME="$1"
SERVERIP="$2"
ZABBIXCONF="/etc/zabbix_agent2.conf"

if ! grep -q "excludepkgs=zabbix" /etc/yum.repos.d/epel.repo; then
	sed -i '/\[epel\]/a excludepkgs=zabbix*' /etc/yum.repos.d/epel.repo
fi

rpm -Uvh https://repo.zabbix.com/zabbix/7.4/release/rhel/9/noarch/zabbix-release-latest.el9.noarch.rpm

dnf update

# Does nothing in AlmaLinux 9
# yum-config-manager --enable rhel-7-server-optional-rpms > /dev/null

./uesp-yuminstall zabbix-agent2

systemctl enable zabbix-agent2
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to add the Zabbix agent startup script using systemctl!"
	exit -6
fi

sed -i "s/^Server=.*/Server=$SERVERIP/g" "$ZABBIXCONF"
sed -i "s/^ServerActive=.*/ServerActive=$SERVERIP/g" "$ZABBIXCONF"
sed -i "s/^Hostname=.*/Hostname=$UESP_HOSTNAME/g" "$ZABBIXCONF"

service zabbix-agent2 restart

# sed -i "s/Server=(.*)/Server=10.12.222.25/g" "/etc/zabbix/zabbix_agent2.conf"

echo "     OK: Successfully installed the Zabbix agent!"
