#!/bin/sh

echo "Starting uesp-update-rpm..."

# rpm --quiet -Uhv http://apt.sw.be/redhat/el5/en/i386/rpmforge/RPMS/rpmforge-release-0.3.6-1.el5.rf.i386.rpm > /dev/null
rpm -Uvh remi-release-6*.rpm epel-release-6*.rpm

# Force update of package files
#yum -q list memcached > /dev/null
yum update

echo "     OK: Successfully updated the rpm package."
exit 0
