#!/bin/sh
#
# $1 = IP to bind memcached server to
#
# ./uesp-yuminstall "libevent-devel"

./uesp-yuminstall "memcached"

SERVERIP="$1"

if [ -z $SERVERIP ]
then
	echo "     WARNING: Missing memcached server IP address, using default of 127.0.0.1!"
	SERVERIP="127.0.0.1"
fi

sed "s:^\([ ^I]*MEMCACHEDIP[ ^I]*=[ ^I]*\)\".*\":\1\"$SERVERIP\":" ./memcached.initd > /etc/init.d/memcached

if [ $? != 0 ]
then
	echo "     ERROR: Failed to setup initialization script in '/etc/init.d/'!"
	exit -6
fi

chmod 755 /etc/init.d/memcached
/sbin/chkconfig --add memcached

if [ $? != 0 ]
then
	echo "     ERROR: Failed to add initialization script chkconfig!"
	exit -7
fi

/etc/init.d/memcached restart > /dev/null

if [ $? != 0 ]
then
	echo "     ERROR: Failed to start memcached!"
	exit -8
fi

echo "     OK: Successfully installed memcached."
exit 0
