#!/bin/sh

echo "Starting uesp-update-yum..."

./uesp-yuminstall "yum-utils"
./uesp-yuminstall "epel-release"
yum -q -y install http://rpms.remirepo.net/enterprise/remi-release-7.rpm

yum-config-manager --enable remi-php56 > /dev/null

curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo | sudo tee /etc/yum.repos.d/salt.repo

./uesp-update-yumapps

echo "     OK: Successfully updated yum."
exit 0
