#!/bin/sh

CONFIGPATH="/etc/salt"
LOCALHOSTNAME=`hostname`
SHORTHOSTNAME=`hostname -s`

echo "Setting up the salt minion..."

# This is probably already done but just in case
./uesp-yuminstall "salt-minion"

echo "$LOCALHOSTNAME" > "$CONFIGPATH/minion_id"

if [ $? != 0 ]
then
	echo "     ERROR: Failed to set the minion_id!"
	exit -2
fi

cp ./salt.minion/*.conf "$CONFIGPATH/minion.d/"

if [ $? != 0 ]
then
	echo "     ERROR: Failed to copy the config files!"
	exit -3
fi

sed -i "s/^id:.*/id: $SHORTHOSTNAME/g" "$CONFIGPATH/minion.d/id.conf"

if [ $? != 0 ]
then
	echo "     ERROR: Failed to modify the minion id.conf file!"
	exit -4
fi

systemctl enable salt-minion
systemctl start salt-minion

if [ $? != 0 ]
then
	echo "     ERROR: Failed to start the salt.minion!"
	exit -4
fi

echo "Finished setting up the salt minion!"