#!/bin/sh

CONFIGPATH="/etc/salt"
LOCALHOSTNAME=`hostname`
SHORTHOSTNAME=`hostname -s`

echo "Setting up the salt minion..."

echo "$LOCALHOSTNAME" > "$CONFIGPATH/minion_id"

if [ $? != 0 ]
then
	echo "     ERROR: Failed to set the minion_id!"
	return -2
fi

cp "./salt.minion/*.conf" "$CONFIGPATH/minion.d/"

if [ $? != 0 ]
then
	echo "     ERROR: Failed to copy the config files!"
	return -3
fi

sed -i "s/^id:.*/id: $SHORTHOSTNAME/g" "$CONFIGPATH/minion.d/id.conf"

if [ $? != 0 ]
then
	echo "     ERROR: Failed to modify the minion id.conf file!"
	return -4
fi

echo "Finished setting up the salt minion!"