#!/bin/sh
#
# $1 = Server IP address
#

SERVERIP="$1"

if [ -z $SERVERIP ]
then
	echo "     ERROR: Missing Zabbix Server IP address!"
	exit -1
fi

./uesp-yuminstall "php-gd"
./uesp-yuminstall "php-bcmath"
./uesp-yuminstall "php-xml"
./uesp-yuminstall "php-mbstring"
./uesp-yuminstall "php-mysqlnd"
./uesp-yuminstall "php-snmp"

./uesp-yuminstall "pcre"
./uesp-yuminstall "pcre-devel"
./uesp-yuminstall "pcre-static"
# ./uesp-yuminstall "libpthread" # Included with glibc
./uesp-yuminstall "zlib"
./uesp-yuminstall "zlib-devel"
./uesp-yuminstall "zlib-static"

./uesp-yuminstall "libevent"
./uesp-yuminstall "fping"
./uesp-yuminstall "OpenIPMI"
./uesp-yuminstall "libssh2"
./uesp-yuminstall "libcurl"
./uesp-yuminstall "libxml2"
./uesp-yuminstall "net-snmp"
./uesp-yuminstall "net-snmp-libs"
./uesp-yuminstall "net-snmp-utils"

./uesp-yuminstall "java-11-openjdk-devel"

if ! grep -q "excludepkgs=zabbix" /etc/yum.repos.d/epel.repo; then
	sed -i '/\[epel\]/a excludepkgs=zabbix*' /etc/yum.repos.d/epel.repo
fi

rpm -Uvh https://repo.zabbix.com/zabbix/7.4/release/rhel/9/noarch/zabbix-release-latest.el9.noarch.rpm

dnf update

./uesp-yuminstall zabbix-server-mysql
./uesp-yuminstall zabbix-web-mysql

systemctl enable zabbix-server
# service zabbix-server restart

echo "     OK: Installed the Zabbix Server."

./uesp-install-zabbixagent "$SERVERIP"
