#!/bin/sh

echo "Starting base app installation..."

./uesp-install-hg
./uesp-install-git

./uesp-yuminstall "at"
./uesp-yuminstall "vsftpd"
./uesp-yuminstall "libmcrypt"
./uesp-yuminstall "libtool-ltdl"
./uesp-yuminstall "gcc"
./uesp-yuminstall "gcc-c++"
./uesp-yuminstall "ntp"
./uesp-yuminstall "nfs-utils"
./uesp-yuminstall "re2c"
./uesp-yuminstall "curl"
./uesp-yuminstall "libcurl-devel"
./uesp-yuminstall "bind-utils"

./uesp-yuminstall "python"
./uesp-yuminstall "MySQL-python"

# ./uesp-yuminstall "swig"   # ???

systemctl enable atd
systemctl enable ntpd

systemctl start atd
systemctl start ntpd




