#!/bin/sh
#
# $1 = Hostname (prompts if missing)
# $2 = Zabbix Server IP
#

UESP_HOSTNAME="$1"
ZABBIXSERVER="$2"

get_uesp_hostname()
{
	RESULT=""

	if [ -z "$UESP_HOSTNAME" ]
	then
		echo -n "Enter UESP host subdomain: "
		read UESP_HOSTNAME
	fi

	UESP_HOSTNAME=`echo $UESP_HOSTNAME | tr '[:upper:]' '[:lower:]'`

	if [ -z $UESP_HOSTNAME ]
	then
		echo "     ERROR: Empty UESP host subdomain given!"
		exit -1
	else
		echo "     OK: Using UESP host name '$UESP_HOSTNAME'."
	fi
}

get_zabbix_server_ip()
{
	RESULT=""

	if [ -z "$ZABBIXSERVER" ]
	then
		echo -n "Enter the Zabbix Server IP Address: "
		read ZABBIXSERVER
	fi

	if [ -z $ZABBIXSERVER ]
	then
		echo "     WARNING: Skipping Zabbix Agent installation due to missing server address!"
	else
		echo "     OK: Using Zabbix Server IP '$ZABBIXSERVER'."
	fi
}

echo "Starting uesp-setup-common..."

get_uesp_hostname
get_zabbix_server_ip

./uesp-update-hostname "$UESP_HOSTNAME"
./uesp-create-localkey  "$UESP_HOSTNAME"

./uesp-create-users
./uesp-update-yum
./uesp-install-baseapps
./uesp-update-sshd
./uesp-install-denyhosts
./uesp-update-path
./uesp-update-maxfiles
./uesp-update-bashrc ""

if [ ! -z "$ZABBIXSERVER" ]
then
	./uesp-install-zabbixagent "$UESP_HOSTNAME" "$ZABBIXSERVER" 
fi

