#!/bin/sh
#
# $1 = Server IP address
#

SERVERIP="$1"

if [ -z $SERVERIP ]
then
	echo "     ERROR: Missing Zabbix Server IP address!"
	exit -1
fi

yum-config-manager --enable remi-php56 > /dev/null

./uesp-yuminstall "php-gd"
./uesp-yuminstall "php-bcmath"
./uesp-yuminstall "php-xml"
./uesp-yuminstall "php-mbstring"
./uesp-yuminstall "php-mysqlnd"
./uesp-yuminstall "php-snmp"

./uesp-yuminstall "pcre"
./uesp-yuminstall "pcre-devel"
./uesp-yuminstall "pcre-static"
# ./uesp-yuminstall "libpthread" # Included with glibc
./uesp-yuminstall "zlib"
./uesp-yuminstall "zlib-devel"
./uesp-yuminstall "zlib-static"

./uesp-yuminstall "libevent"
./uesp-yuminstall "fping"
./uesp-yuminstall "OpenIPMI"
./uesp-yuminstall "libssh2"
./uesp-yuminstall "libcurl"
./uesp-yuminstall "libxml2"
./uesp-yuminstall "net-snmp"
./uesp-yuminstall "net-snmp-libs"
./uesp-yuminstall "net-snmp-utils"

rpm -Uvh https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
yum-config-manager --enable rhel-7-server-optional-rpms > /dev/null

./uesp-yuminstall zabbix-server-mysql
./uesp-yuminstall zabbix-web-mysql

systemctl enable zabbix-server
# service zabbix-server restart

echo "     OK: Installed the Zabbix Server."

./uesp-install-zabbixagent "$SERVERIP"
