#!/bin/sh

add_host_entry()
# $1 = IP address to add to allow list
{
	./uesp-addhostentry "/etc/hosts.allow" "portmap" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "rpcbind" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "statd" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "lockd" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "mountd" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "quotad" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "rquotad" "$1"
	
	return 0
}

add_exports_entry()
# $1 = IP address to add to exports
{
	./uesp-addexportsentry  "/shared"      "$1"
}

./uesp-yuminstall "nfs-utils"

systemctl enable rpcbind
systemctl enable nfs-server
systemctl enable nfs-lock
systemctl enable nfs-idmap

systemctl start rpcbind
systemctl start nfs-server
systemctl start nfs-lock
systemctl start nfs-idmap

add_exports_entry "10.12.123.11"
add_exports_entry "10.12.123.18"
add_exports_entry "10.12.123.19"
add_exports_entry "10.12.123.12"
add_exports_entry "10.12.123.17"

add_exports_entry "107.161.64.230"
add_exports_entry "107.161.64.231"
add_exports_entry "107.161.64.232"
add_exports_entry "107.161.64.239"
add_exports_entry "107.161.64.233"

/usr/sbin/exportfs -ra

systemctl restart nfs-server
