#!/bin/sh

mount_path()
#
# $1 = Files Server
# $2 = Remote Path
# $3 = Local Path
#
{
	SERVER="$1"
	REMOTEPATH="$2"
	LOCALPATH="$3"
	
	if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
	then
		echo "     ERROR: Missing parameters in call to function mount_path(Server, RemotePath, LocalPath)!"
		return -1
	fi
	
	./uesp-addfstabentry "$SERVER" "$REMOTEPATH" "$LOCALPATH"

	echo "Unmounting $LOCALPATH ..."
	umount "$LOCALPATH" 2> /dev/null
	
	echo "Mounting $LOCALPATH ..."
	mount $SERVER:$REMOTEPATH "$LOCALPATH" > /dev/null
	
	if [ $? != 0 ]
	then
		echo "     ERROR: Failed to mount '$LOCALPATH' to '$SERVER:$REMOTEPATH'!"
		return -2
	fi

	echo "     OK: Mounted '$LOCALPATH' to '$SERVER:$REMOTEPATH'."
	return 0
}

add_host_entry()
# $1 = IP address to add to allow list
{
	./uesp-addhostentry "/etc/hosts.allow" "portmap" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "rpcbind" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "statd" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "lockd" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "mountd" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "quotad" "$1"
	./uesp-addhostentry "/etc/hosts.allow" "rquotad" "$1"
	
	return 0
}

./uesp-yuminstall "nfs-utils"

rmdir /mnt/uesp
rmdir /mnt/fallout
rmdir /mnt/sfwiki

mkdir -p /mnt/shared

if [ ! -e "/mnt/uesp" ]; then
	ln -s /mnt/shared/uesp /mnt/uesp
	ln -s /mnt/shared/sfwiki /mnt/sfwiki
	ln -s /mnt/shared/fallout /mnt/fallout
fi

	# Run this on the new servers
mount_path "10.12.123.16" "/shared" "/mnt/shared"

	# Run this on the old servers
# mount_path "184.107.171.220" "/shared" "/mnt/shared"




