#!/bin/sh
#
# $1 = Server IP address
#

SERVERIP="$1"

if [ -z $SERVERIP ]
then
	echo "     ERROR: Missing Zabbix Server IP address!"
	exit -1
fi

./uesp-install-contentapps

./uesp-yuminstall "OpenIPMI"
./uesp-yuminstall "libssh2"

./uesp-yuminstall "mysql-server"
./uesp-yuminstall "mysql-devel"

./uesp-yuminstall "net-snmp"
./uesp-yuminstall "net-snmp-devel"
./uesp-yuminstall "net-snmp-libs"
./uesp-yuminstall "net-snmp-perl"
./uesp-yuminstall "net-snmp-utils"
./uesp-yuminstall "php-snmp"

/sbin/chkconfig --level 345 mysqld on

if [ $? != 0 ]
then
	echo "     ERROR: Failed to modify run levels for mysqld!"
	exit -1
fi

echo "     OK: Modified run levels for mysqld."

mkdir -p /usr/kerberos/lib

if [ $? != 0 ]
then
	echo "     ERROR: Failed to create directory '/usr/kerberos/lib'!"
	exit -2
fi

echo "     OK: Created directory '/usr/kerberos/lib'."
ln -f -s /usr/lib/libcurl.* /usr/kerberos/lib

if [ $? != 0 ]
then
	echo "     ERROR: Failed to create symbolic links to libcurl libraries in '/usr/kerberos/lib'!"
	exit -3
fi

echo "     OK: Created symbolic links to libcurl libraries in '/usr/kerberos/lib'."

pushd . > /dev/null
cd zabbix-src
./configure --enable-server --enable-agent --with-mysql --with-net-snmp --enable-libcurl

if [ $? != 0 ]
then
	echo "     ERROR: Failed to configure Zabbix server source!"
	exit -4
fi

make

if [ $? != 0 ]
then
	echo "     ERROR: Failed to make Zabbix server source!"
	exit -4
fi

make install

if [ $? != 0 ]
then
	echo "     ERROR: Failed to install the Zabbix server!"
	exit -4
fi

cp ./zabbix_server /etc/init.d/

if [ $? != 0 ]
then
	echo "     ERROR: Failed to install zabbix script to /etc/init.d/!"
	exit -5
fi

popd > /dev/null
echo "     OK: Installed the Zabbix Server."

./uesp-install-zabbixagent "$SERVERIP"
