#!/bin/sh

./uesp-yuminstall "mariadb"

# Not required in AlmaLinux
# yum-config-manager --enable remi-php56 > /dev/null

	# FFMpeg: Not working in AlmaLinux 8
# rpm --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro
# rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
# ./uesp-yuminstall "ffmpeg"
# ./uesp-yuminstall "ffmpeg-devel"
# ./uesp-yuminstall "ffmpeg2theora"

	# Custom ffmpeg install...not tested
echo "WARNING: Installing untested ffmpeg..."
pushd /home/uesp/
wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
tar xvf ffmpeg-git-amd64-static.tar.xz
mv -f ffmpeg-git-20240629-amd64-static ffmpeg
chown uesp:uespadmin /home/uesp/ffmpeg/
chmod g+rwx /home/uesp/ffmpeg/
popd
echo "Finished installing untested ffmpeg!"

./uesp-yuminstall "lua"
 
 # Default install is PHP v8.0 on AlmaLinux 9
./uesp-yuminstall "php"
./uesp-yuminstall "php-common"
./uesp-yuminstall "php-devel"
./uesp-yuminstall "php-bcmath"
./uesp-yuminstall "php-cli"
./uesp-yuminstall "php-gd"
./uesp-yuminstall "php-intl"
./uesp-yuminstall "php-mbstring"
# ./uesp-yuminstall "php-mcrypt"
./uesp-yuminstall "php-mysqlnd"
./uesp-yuminstall "php-opcache"
./uesp-yuminstall "php-pdo"
./uesp-yuminstall "php-pear"
./uesp-yuminstall "php-pecl-apcu"
./uesp-yuminstall "php-pecl-imagick"
# ./uesp-yuminstall "php-pecl-luasandbox"
./uesp-yuminstall "php-pecl-memcache"
./uesp-yuminstall "php-pecl-memcached"
# ./uesp-yuminstall "php-pecl-runkit7"
./uesp-yuminstall "php-pecl-zip"
./uesp-yuminstall "php-process"
./uesp-yuminstall "php-snmp"
./uesp-yuminstall "php-xml"

./uesp-yuminstall "php71-php-common"
./uesp-yuminstall "php71-php-cli"
./uesp-yuminstall "php71-php-fpm"
./uesp-yuminstall "php71-php-bcmath"
./uesp-yuminstall "php71-php-gd"
./uesp-yuminstall "php71-php-intl"
./uesp-yuminstall "php71-php-jsonc"
./uesp-yuminstall "php71-php-mbstring"
./uesp-yuminstall "php71-php-mcrypt"
./uesp-yuminstall "php71-php-mysqlnd"
./uesp-yuminstall "php71-php-opcache"
./uesp-yuminstall "php71-php-pdo"
./uesp-yuminstall "php71-php-pecl-apcu"
./uesp-yuminstall "php71-php-pecl-igbinary"
./uesp-yuminstall "php71-php-pecl-imagick-im6"
./uesp-yuminstall "php71-php-pecl-lua"
./uesp-yuminstall "php71-php-pecl-memcache"
./uesp-yuminstall "php71-php-pecl-memcached"
./uesp-yuminstall "php71-php-pecl-msgpack"
./uesp-yuminstall "php71-php-pecl-mysql"
./uesp-yuminstall "php71-php-pecl-runkit7"
./uesp-yuminstall "php71-php-pecl-xhprof"
./uesp-yuminstall "php71-php-pecl-zip"
./uesp-yuminstall "php71-php-snmp"
./uesp-yuminstall "php71-php-xml"

./uesp-yuminstall "php74-php-common"
./uesp-yuminstall "php74-php-cli"
./uesp-yuminstall "php74-php-fpm"
./uesp-yuminstall "php74-php-bcmath"
./uesp-yuminstall "php74-php-gd"
./uesp-yuminstall "php74-php-intl"
./uesp-yuminstall "php74-php-json"
./uesp-yuminstall "php74-php-mbstring"
./uesp-yuminstall "php74-php-mysqlnd"
./uesp-yuminstall "php74-php-opcache"
./uesp-yuminstall "php74-php-pdo"
./uesp-yuminstall "php74-php-pecl-apcu"
./uesp-yuminstall "php74-php-pecl-igbinary"
./uesp-yuminstall "php74-php-pecl-imagick-im6"
./uesp-yuminstall "php74-php-pecl-lua"
./uesp-yuminstall "php74-php-pecl-mcrypt"
./uesp-yuminstall "php74-php-pecl-memcache"
./uesp-yuminstall "php74-php-pecl-memcached"
./uesp-yuminstall "php74-php-pecl-msgpack"
./uesp-yuminstall "php74-php-pecl-mysql"
./uesp-yuminstall "php74-php-pecl-runkit7"
./uesp-yuminstall "php74-php-pecl-xhprof"
./uesp-yuminstall "php74-php-pecl-zip"
./uesp-yuminstall "php74-php-snmp"
./uesp-yuminstall "php74-php-xml"

./uesp-yuminstall "php80-php-common"
./uesp-yuminstall "php80-php-cli"
./uesp-yuminstall "php80-php-fpm"
./uesp-yuminstall "php80-php-bcmath"
./uesp-yuminstall "php80-php-gd"
./uesp-yuminstall "php80-php-intl"
./uesp-yuminstall "php80-php-mbstring"
./uesp-yuminstall "php80-php-mysqlnd"
./uesp-yuminstall "php80-php-opcache"
./uesp-yuminstall "php80-php-pdo"
./uesp-yuminstall "php80-php-pecl-apcu"
./uesp-yuminstall "php80-php-pecl-igbinary"
./uesp-yuminstall "php80-php-pecl-imagick-im6"
./uesp-yuminstall "php80-php-pecl-luasandbox"
./uesp-yuminstall "php80-php-pecl-mcrypt"
./uesp-yuminstall "php80-php-pecl-memcache"
./uesp-yuminstall "php80-php-pecl-memcached"
./uesp-yuminstall "php80-php-pecl-msgpack"
./uesp-yuminstall "php80-php-pecl-mysql"
./uesp-yuminstall "php80-php-pecl-runkit7"
./uesp-yuminstall "php80-php-pecl-xhprof"
./uesp-yuminstall "php80-php-pecl-zip"
./uesp-yuminstall "php80-php-snmp"
./uesp-yuminstall "php80-php-xml"

./uesp-yuminstall "gnuplot"
./uesp-yuminstall "pkgconf"

# ./uesp-yuminstall "perl"
# ./uesp-yuminstall "perl-DBD-MySQL"
# ./uesp-yuminstall "perl-DBI"
# ./uesp-yuminstall "perl-String-CRC32"
# ./uesp-yuminstall "perl-URI"

./uesp-yuminstall "httpd"
./uesp-yuminstall "mod_ssl"
./uesp-install-modevasive
systemctl enable httpd

./uesp-yuminstall "ImageMagick"
./uesp-yuminstall "tidy"
./uesp-yuminstall "fail2ban"

./uesp-install-wikidiff2

	# Ensure that any extra Apache logging has access to the log directory
mkdir -p /var/log/httpd/
chown apache:apache -R /var/log/httpd
chmod a+rx /var/log

