#!/bin/sh

echo "Starting uesp-install-denyhosts..."

#./uesp-yuminstall "python"
# ./uesp-yuminstall "python-ipaddr"
./uesp-yuminstall "python3"
./uesp-yuminstall "python3-types-ipaddress"

pushd denyhosts > /dev/null

python setup.py install
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to install the DenyHosts Python application!"
	popd
	exit -1
fi

HOSTNAME=`hostname`
sed -i -e"s/^PURGE_DENY =.*/PURGE_DENY = 2w/" /etc/denyhosts.conf

if [ $? != 0 ]
then
	echo "     WARNING: Failed to modify denyhosts PURGE_DENY setting!"
fi

sed -i -e"s/nobody@localhost/denyhosts@$HOSTNAME/" /etc/denyhosts.conf

if [ $? != 0 ]
then
	echo "     WARNING: Failed to modify denyhosts send e-mail address!"
fi

mv -f /usr/local/bin/daemon-control-dist /usr/local/bin/denyhosts-daemon-control
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to create the DenyHosts daemon file!"
	popd
	exit -2
fi

chown root /usr/local/bin/denyhosts-daemon-control
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to change the owner of the DenyHosts daemon-control file!"
	popd
	exit -3
fi

chmod 700 /usr/local/bin/denyhosts-daemon-control
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to change the permissions of the DenyHosts daemon-control file!"
	popd
	exit -4
fi

if [ ! -d /var/log/denyhosts ]
then
	mkdir -p /var/log/denyhosts
	RESULT=$?

	if [ $RESULT != 0 ]
	then
		echo "     WARNING: Failed to create the DenyHosts log directory '/var/log/denyhosts'!"
	fi
fi

sed -i "s/^DAEMON_LOG =.*/DAEMON_LOG = \/var\/log\/denyhosts\/denyhosts.log/g" /etc/denyhosts.conf

ln -fs /usr/local/bin/denyhosts.py /usr/sbin/denyhosts.py
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to create /usr/sbin/denyhosts.py entry!"
	popd
	exit -5
fi

ln -fs /usr/local/bin/denyhosts.py /usr/sbin/denyhosts
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to create /usr/sbin/denyhosts entry!"
	popd
	exit -5
fi

LINE="denyhosts-daemon-control start"
FILE=/etc/rc.d/rc.local
grep -q "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to add DenyHosts startup script to '/etc/rc.local'!"
	popd
	exit -5
fi

denyhosts-daemon-control start
RESULT=$?

if [ $RESULT != 0 ]
then
	echo "     ERROR: Failed to start DenyHosts!"
	popd
	exit -8
fi

echo "     OK: Successfully started DenyHosts!"

popd > /dev/null

echo "     OK: Installed the DenyHosts Python application."
exit 0
