/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_WIKIDIFF2_H
#define PHP_WIKIDIFF2_H

extern zend_module_entry wikidiff2_module_entry;
#define phpext_wikidiff2_ptr &wikidiff2_module_entry

#ifdef PHP_WIN32
# define PHP_WIKIDIFF2_API __declspec(dllexport)
#else
# define PHP_WIKIDIFF2_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(wikidiff2);
PHP_MSHUTDOWN_FUNCTION(wikidiff2);
PHP_RINIT_FUNCTION(wikidiff2);
PHP_RSHUTDOWN_FUNCTION(wikidiff2);
PHP_MINFO_FUNCTION(wikidiff2);

ZEND_NAMED_FUNCTION(_wrap_wikidiff2_do_diff);
#endif /* PHP_WIKIDIFF2_H */
