<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('wikidiff2')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_wikidiff2.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('wikidiff2.so')) return;
    } else {
      if (!dl('wikidiff2.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class wikidiff2 {
	static function wikidiff2_do_diff($text1,$text2,$num_lines_context) {
		return wikidiff2_do_diff($text1,$text2,$num_lines_context);
	}
}

/* PHP Proxy Classes */

?>
